version: '3.0'

services:
  bin:
    build:
      context: .
      dockerfile: Dockerfile
    command: cargo tarpaulin -v
    volumes: 
      - .:/usr/src/app
      - registry:/root/.cargo/registry

volumes:
  registry:
    driver: local